name: Android CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # מאפשר לך להריץ את הבנייה באופן ידני בלחיצת כפתור בטאב Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # שלב עוקף נטפרי: משנים את שם קובץ ה-APK לגרסת קובץ נתונים (.dat) כדי שהסינון לא יחסום את ההורדה שלו
    - name: Prepare File for NetFree Bypass
      run: |
        mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/app-debug.dat

    # העלאת הקובץ לשרתי גיטהאב לצורך הורדה
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-App-Safe-Download
        path: app/build/outputs/apk/debug/app-debug.dat
